language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'

before_install:
  - pip install --upgrade pexpect
  - pip install --upgrade coveralls
  - pip install --upgrade coverage
  - pip install --upgrade futures
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install --upgrade sphinx; fi

script: "nosetests --with-coverage --cover-package=bladerunner"

after_success:
  - coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install --upgrade bladerunner; cd docs; make html; cd -; python setup.py upload_docs --upload-dir=docs/build/html; fi

notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
