language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'

before_install:
  - pip install --upgrade pexpect
  - pip install --upgrade coveralls
  - pip install --upgrade coverage
  - pip install --upgrade futures

script: "nosetests --with-coverage --cover-package=bladerunner"

after_success:
  - coveralls

notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
